[package]
name = "error_derive"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.100", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = { version = "1" }