[package]
name = "error_derive"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0.53", features = ["full", "extra-traits"] }
quote = "1.0.35"
proc-macro2 = { version = "1.0.79" }